# Exchange code to full name mapping for better display
EXCHANGE_CODE_TO_NAME = {
    # Major exchanges
    "NYSE": "New York Stock Exchange",
    "NASDAQ": "NASDAQ Stock Market",
    "LSE": "London Stock Exchange",
    "TSE": "Tokyo Stock Exchange",
    "FRA": "Frankfurt Stock Exchange",
    "PAR": "Euronext Paris",
    "AMS": "Euronext Amsterdam",
    "MIL": "Borsa Italiana",
    "MAD": "Bolsa de Madrid",
    "STO": "Stockholm Stock Exchange",
    "OSL": "Oslo Stock Exchange",
    "CPH": "Copenhagen Stock Exchange",
    "HEL": "Helsinki Stock Exchange",
    "BRU": "Euronext Brussels",
    "DUB": "Irish Stock Exchange",
    "LIS": "Euronext Lisbon",
    "VIE": "Vienna Stock Exchange",
    "WAR": "Warsaw Stock Exchange",
    "ATH": "Athens Stock Exchange",
    "BUD": "Budapest Stock Exchange",
    "PRA": "Prague Stock Exchange",
    "IST": "Istanbul Stock Exchange",
    "MEX": "Mexican Stock Exchange",
    "HKG": "Hong Kong Stock Exchange",
    "SGX": "Singapore Exchange",
    "TWO": "Taiwan Stock Exchange",
    "KLSE": "Bursa Malaysia",
    "KRX": "Korea Exchange",
    "NSE": "National Stock Exchange of India",
    "BSE": "Bombay Stock Exchange",
    "SSE": "Shanghai Stock Exchange",
    "SZSE": "Shenzhen Stock Exchange",
    "SET": "Stock Exchange of Thailand",
    "IDX": "Indonesia Stock Exchange",
    "PSE": "Philippine Stock Exchange",
    "HOSE": "Ho Chi Minh Stock Exchange",
    "ASX": "ASX",
    "SIX": "Swiss Exchange",
    "TSX": "Toronto Stock Exchange",
    "TSXV": "TSX Venture Exchange",

    # Country codes that are being used as exchanges in the Stock Database
    "US": "United States Markets",
    "CA": "Canadian Markets",
    "UK": "United Kingdom Markets",
    "JP": "Japanese Markets",
    "DE": "German Markets",
    "FR": "French Markets",
    "AU": "Australian Markets",
    "CH": "Swiss Markets",
    "NL": "Dutch Markets",
    "IT": "Italian Markets",
    "ES": "Spanish Markets",
    "SE": "Swedish Markets",
    "NO": "Norwegian Markets",
    "DK": "Danish Markets",
    "FI": "Finnish Markets",
    "BE": "Belgian Markets",
    "IE": "Irish Markets",
    "PT": "Portuguese Markets",
    "AT": "Austrian Markets",
    "PL": "Polish Markets",
    "GR": "Greek Markets",
    "HU": "Hungarian Markets",
    "CZ": "Czech Markets",
    "TR": "Turkish Markets",
    "MX": "Mexican Markets",
    "HK": "Hong Kong Markets",
    "SG": "Singapore Markets",
    "TW": "Taiwan Markets",
    "MY": "Malaysian Markets",
    "KR": "South Korean Markets",
    "IN": "Indian Markets",
    "CN": "Chinese Markets",
    "TH": "Thai Markets",
    "ID": "Indonesian Markets",
    "PH": "Philippine Markets",
    "VN": "Vietnamese Markets"
}

def get_exchange_display_name(exchange_code):
    """Convert exchange code to full display name"""
    return EXCHANGE_CODE_TO_NAME.get(exchange_code, exchange_code)
